version: '3.7'
services:
  mongo:
    image: mongo:4.4.15
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=alex
      - ME_CONFIG_BASICAUTH_PASSWORD=password
  api:
    image: alexlowe64/ferguson-api:latest
    ports:
      - 10003:10003

volumes:
  mongodb_data_container:
